spring:
  main:
    allow-bean-definition-overriding: true
  liquibase:
    url: jdbc:postgresql://localhost:${datasource.port}/${datasource.database}
    user: ${datasource.username}
    password: ${datasource.password}
    change-log: classpath:db/changelog.xml
  r2dbc:
    url: r2dbc:postgresql://localhost:${datasource.port}/${datasource.database}
    username: ${datasource.username}
    password: ${datasource.password}
  profiles:
    active: live

datasource:
  host: localhost
  port: 5432
  username: user
  password: pass
  database: r2dbc_db