spring:
  main:
    allow-bean-definition-overriding: true
  liquibase:
    url: jdbc:postgresql://localhost:5432/r2dbc_db
    user: user
    password: pass
    change-log: classpath:db/changelog.xml
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/r2dbc_db
    username: user
    password: pass
  profiles:
    active: live

datasource:
  host: localhost
  port: 5432
  username: user
  password: pass
  database: r2dbc_db